Code/Bringly.UI/Controllers/MenuController.cs
using Bringly.Domain;
using Bringly.Domain.User;
using Bringly.DomainLogic;
using Bringly.DomainLogic.User;
using System;
using System.Web.Mvc;

namespace Bringly.UI.Controllers
{
    public class MenuController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [ChildActionOnlyAttribute]
        public PartialViewResult ChoosePreferedCity()
        {
            CommonDomainLogic commonDomainLogic = new CommonDomainLogic();
            UserDomainLogic _userDomainLogic = new UserDomainLogic();
            ChooseCity chooseCity = new ChooseCity();
            UserProfile _FindUser = _userDomainLogic.FindUser(UserVariables.LoggedInUserGuid);
            chooseCity.Cities = commonDomainLogic.GetCities();
            chooseCity.SelectedCity = commonDomainLogic.GetPreferedCity();
            chooseCity.TopCities = commonDomainLogic.GetTopCities(chooseCity.SelectedCity);
            return PartialView("_chooseCity", chooseCity);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public PartialViewResult TopMenu()
        {
            EmailDomainLogic email = new EmailDomainLogic();
            return PartialView("_topUserMenu",email.GetNotificationEmail(Guid.Empty));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public PartialViewResult SocialUserTopMenu()
        {
            return PartialView("_topSocialUserMenu");
        }
    }
}

Code/Bringly.UI/Controllers/UserController.cs
using Bringly.Domain;
using Bringly.Domain.Common;
using Bringly.Domain.Enums;
using Bringly.Domain.User;
using Bringly.DomainLogic;
using Bringly.DomainLogic.Business;
using Bringly.DomainLogic.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using Utilities;

namespace Bringly.UI.Controllers
{
    public class UserController : BaseClasses.AuthoriseUserControllerBase
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Dashboard()
        {
            UserDomainLogic userdomainLogic = new UserDomainLogic();
            Dashboard dashboard = new Dashboard();
            OrderDomainLogic orderDomainLogic = new OrderDomainLogic();
            WalletDomainLogic walletDomainLogic = new WalletDomainLogic();
            dashboard.MyMessage = userdomainLogic.GetMyMessages(UserVariables.LoggedInUserGuid);

            if (UserVariables.UserRole == Bringly.Domain.Enums.User.UserRoles.Buyer)
                dashboard.MyFavourites = userdomainLogic.FavouriteLocations(2);

            else dashboard.MyFavourites = null;

            if (UserVariables.UserRole == Bringly.Domain.Enums.User.UserRoles.Merchant)
            {
                MyReview myreview = new MyReview();
                myreview.UserGuid = UserVariables.LoggedInUserGuid;
                dashboard.MyReview = userdomainLogic.GetMyReviewMerchant(myreview);
                dashboard.MyReview.GivenBusinessReviews = dashboard.MyReview.GivenBusinessReviews.Count > 0 ? dashboard.MyReview.GivenBusinessReviews.Take(2).ToList() : dashboard.MyReview.GivenBusinessReviews;
            }

            dashboard.Wallet = walletDomainLogic.GetWallet(UserVariables.LoggedInUserGuid);
            dashboard.MyOrder = orderDomainLogic.GetMyOrderCounts(UserVariables.LoggedInUserGuid, UserVariables.UserRole);

            return View(dashboard);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult PersonalInformation()
        {
            UserDomainLogic userProfile = new UserDomainLogic();
            if (TempData["Success"] != null)
                Success(TempData["Success"].ToString());
            return View(userProfile.FindUser(UserVariables.LoggedInUserGuid));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult EditPersonalInformation()
        {
            UserDomainLogic userDomainLogic = new UserDomainLogic();
            UserProfile userProfile = userDomainLogic.FindUser(UserVariables.LoggedInUserGuid);
            CommonDomainLogic commonDomainLogic = new CommonDomainLogic();
            userProfile.Cities = commonDomainLogic.GetCities();
            return View(userProfile);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="userProfile"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditPersonalInformation(UserProfile userProfile)
        {
            UserDomainLogic userdomainLogic = new UserDomainLogic();
            userProfile.UserAddresses = new List<UserAddress>();
            UserAddress usrAddress = new UserAddress();
            Guid cityGuid = Guid.Empty;
            usrAddress.UserAddressGuid = Guid.Parse(HttpContext.Request.Form["BillingAddress_UserAddressGuid"]);
            usrAddress.Address = Convert.ToString(HttpContext.Request.Form["BillingAddress.Address"]);
            usrAddress.PostCode = Convert.ToString(HttpContext.Request.Form["BillingAddress.PostCode"]);
            Guid.TryParse(HttpContext.Request.Form["BillingAddress.CityGuid"], out cityGuid);
            usrAddress.CityGuid = cityGuid;
            usrAddress.AddressType = Bringly.Domain.Enums.User.UserAddressType.Billing.ToString();
            if (usrAddress.CityGuid != Guid.Empty)
                userProfile.UserAddresses.Add(usrAddress);
            usrAddress = new UserAddress();
            usrAddress.UserAddressGuid = Guid.Parse(HttpContext.Request.Form["ShippingAddress_UserAddressGuid"]);
            usrAddress.Address = Convert.ToString(HttpContext.Request.Form["ShippingAddress.Address"]);
            usrAddress.PostCode = Convert.ToString(HttpContext.Request.Form["ShippingAddress.PostCode"]);
            Guid.TryParse(HttpContext.Request.Form["ShippingAddress.CityGuid"], out cityGuid);
            usrAddress.CityGuid = cityGuid;
            usrAddress.AddressType = Bringly.Domain.Enums.User.UserAddressType.Shipping.ToString();
            userProfile.UserAddresses.Add(usrAddress);
            userdomainLogic.UpdateUserProfile(userProfile);
            TempData["Success"] = "Saved successfully";
            CommonDomainLogic commonDomainLogic = new CommonDomainLogic();
            userProfile.Cities = commonDomainLogic.GetCities();

            return RedirectToAction("PersonalInformation");
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="CityGuid"></param>
        /// <returns></returns>
        public ActionResult UpdatePreferedCity(Guid CityGuid)
        {
            UserDomainLogic userDomainLogic = new UserDomainLogic();
            userDomainLogic.UpdatePreferedCity(CityGuid);
            return null;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="restaurantGuid"></param>
        /// <param name="IsFavourite"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult AddToFavourite(string restaurantGuid, string IsFavourite)
        {
            UserDomainLogic userDomainLogic = new UserDomainLogic();
            return Json(userDomainLogic.AddFavourite(Guid.Parse(restaurantGuid), IsFavourite), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="restaurantGuid"></param>
        /// <param name="IsFavourite"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult RemoveFavourite(Guid restaurantGuid, string IsFavourite)
        {
            UserDomainLogic userDomainLogic = new UserDomainLogic();
            return Json(userDomainLogic.RemoveFavourite(restaurantGuid, IsFavourite), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Favourites()
        {
            UserDomainLogic userDomainLogic = new UserDomainLogic();
            return View(userDomainLogic.FavouriteLocations());
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult partialLeftPanel()
        {
            UserDomainLogic userDomainLogic = new UserDomainLogic();
            return View("_LeftPanel", userDomainLogic.FindUser(UserVariables.LoggedInUserGuid));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="frm"></param>
        /// <returns></returns>
        public ActionResult UploadProfileImage(FormCollection frm)
        {
            if (Request.Files.Count > 0)
            {
                try
                {
                    string imageName = "";
                    if (Request.Files.Count > 0)
                    {
                        UserDomainLogic userdomainLogic = new UserDomainLogic();
                        imageName = userdomainLogic.UpdateProfileImage(Request);
                    }
                    return Json(new { NewImage = imageName, Message = "File uploaded successfully", IsSuccess = true });
                }
                catch (Exception ex)
                {
                    return Json(new { NewImage = "", Message = "Error occurred. Error details: " + ex.Message, IsSuccess = false });
                }
            }
            else
            {
                return Json(new { NewImage = "", Message = "No image selected.", IsSuccess = false });
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult SignOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Home");
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult RestaurantReview()
        {
            if (TempData["IspopUp"] != null)
            {
                Success("Review added successfully");
            }

            int Currentpage = 0;
            TempData["CurrentPage"] = null;

            if (Request.Url.AbsoluteUri.Contains('?') && Request.Url.AbsoluteUri.Contains("page"))
            {
                TempData["CurrentPage"] = Request.Url.AbsoluteUri.Split('&')[1].Split('=')[1].Split('&')[0];
                Currentpage = TempData["CurrentPage"] == null ? 0 : Convert.ToInt32(TempData["CurrentPage"]);
                TempData.Keep();
            }

            UserDomainLogic userDomainLogic = new UserDomainLogic();
            return View(userDomainLogic.GetMyReviewBuyer(UserVariables.LoggedInUserGuid, Currentpage));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="ReviewGuid"></param>
        /// <returns></returns>
        public ActionResult AddReview(Guid ReviewGuid)
        {
            UserDomainLogic userDomainLogic = new UserDomainLogic();
            var data = userDomainLogic.GetReviewByGuid(ReviewGuid);
            ViewBag.PopupTitle = "Add Review for " + data.BusinessName;
            return PartialView("_AddReview", data);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="myReview"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddReview(MyReview myReview)
        {

Code/Bringly.UI/Views/Shared/MasterPages/AnonymousUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @{Html.RenderPartial("_pageHeader");}
</head>
<body>
    @{Html.RenderPartial("~/Views/Menu/_topMenu.cshtml");}
    <section class="bg-grey">
        <div class="container">
            @RenderBody()
        </div>
    </section>
    @{Html.RenderPartial("_pageFooter");}
    @RenderSection("scripts", required: false)
</body>
</html>

Code/Bringly.UI/Views/Shared/MasterPages/AuthorizeUserMaster.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @{Html.RenderPartial("_pageHeader");}
    <base href="@HttpContext.Current.Request.Url.AbsoluteUri" />
</head>
<body>
    @if (!Convert.ToBoolean(ViewBag.TopMenuSection))
    {
        Html.RenderAction("TopMenu", "Menu");
    }
    else
    {
        Html.RenderAction("SocialUserTopMenu", "Menu");
    }
    <div class="container">
        @if (!Convert.ToBoolean(ViewBag.BreadcrumSection))
        {
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/User/Dashboard">Home</a></li>
                @RenderSection("BreadCrum", false)
            </ol>
        }
        @if (Bringly.DomainLogic.UserVariables.IsAuthenticated)
        {
            <div class="main-heading">
                <h3>Welcome, @Bringly.DomainLogic.UserVariables.UserName !</h3>
            </div>
        }
        @RenderSection("CustomizeTop", false)
        <div class="dashboard-content inner-margin">
            <div class="row">
                @if (!Convert.ToBoolean(ViewBag.HideLeftSection)) { Html.RenderAction("partialLeftPanel", "User"); }
                @RenderBody()
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
    @{Html.RenderPartial("_pageFooter");}
    @RenderSection("scripts", required: false)
</body>
</html>

Code/Bringly.UI/Views/Shared/MasterPages/PartialMaster.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @{Html.RenderPartial("_pageHeader");}
    <style>
        body {
            overflow-y: auto;
        }

        .body-content {
            height: 560px;
            overflow: auto;
        }
    </style>
</head>
<body class="popup-body inframe">
    <div class="popup-heading">
        <h1>@ViewBag.PopupTitle</h1>
        <div class="close-button">
            <button onclick="window.parent.closeModelPopUpForm(false)" class="btn-close">&times;</button>
        </div>
    </div>
    <div class="body-content">
        @RenderBody()
    </div>
    <div class="clearfix"></div>
    @{Html.RenderPartial("_partialpageFooter");}

    @RenderSection("PageFooterResources", false)
</body>
</html>

Code/Bringly.UI/Views/Shared/MasterPages/RestaurantMaster.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @{Html.RenderPartial("_pageHeader");}
</head>
<body>
    @{Html.RenderAction("TopMenu", "Menu");}

    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/User/Dashboard">Home</a></li>
            @RenderSection("BreadCrum", false)
        </ol>
        <div class="main-heading">
            <h3>@ViewBag.Title</h3>
        </div>
    </div>
    @{Html.RenderAction("BusinessHeader"); }
    <div class="container restaurant-list">
        <div class="dashboard-content inner-margin">
            <div class="row">
                @if (!Convert.ToBoolean(ViewBag.HideLeftSection)) { Html.RenderAction("partialLeftPanel", "User"); }
                @RenderBody()
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    @{Html.RenderPartial("_pageFooter");}
</body>
</html>